### ISSUE TITLE
Problem at the Hessian calculation ValueError: array must not contain infs or NaNs

### ISSUE THREAD

**Issue by rramij** [ruta-k/uGMRTprimarybeam-CASA6#1]
Trying to apply PB correction on a band3 data, but having the following issue.

````
2024-03-14 07:07:42	INFO	widebandpbcor::::casa	Concatenating PBs at all specified frequencies into a cube
2024-03-14 07:07:42	INFO	ImageConcatenator::ImageConcatenator 	Number of images to concatenate = 5
2024-03-14 07:07:42	WARN	ImageConcat::setImage (file casacore/casacore/images/Images/ImageConcat.tcc, line 290)	Images are not contiguous along the concatenation axis For this axis, a non-regular Spectral coordinate will be made
2024-03-14 07:07:42	INFO	SubImageFactory::createImage	Creating image 'test_pb.pbcor.workdirectory/test_pb.pb.cube' of shape [8192, 8192, 1, 5]
2024-03-14 07:07:42	INFO	ImageMaskAttacher::makeMask	Created mask `mask0'
2024-03-14 07:07:53	INFO	widebandpbcor::::casa	Using PBs at [0.31671769927511373, 0.3583396905970866, 0.3999616819190595, 0.4415836732410324, 0.4832056645630053] GHz, to compute Taylor coefficients about 5e-09 GHz
2024-03-14 07:07:57	SEVERE	widebandpbcor::::casa	Task ugmrtpb raised an exception of class ValueError with the following message: array must not contain infs or NaNs
2024-03-14 07:07:57	INFO	ugmrtpb::::casa	Task ugmrtpb complete. Start time: 2024-03-14 09:07:15.591250 End time: 2024-03-14 09:07:57.144982
2024-03-14 07:07:57	INFO	ugmrtpb::::casa	##### End Task: ugmrtpb              #####
2024-03-14 07:07:57	INFO	ugmrtpb::::casa	##########################################
2024-03-14 07:07:57	SEVERE	ugmrtpb::::casa	Exception Reported: Error in ugmrtpb: array must not contain infs or NaNs
2024-03-14 07:07:57	INFO	ugmrtpb::::casa	Traceback (most recent call last):
2024-03-14 07:07:57	INFO	ugmrtpb::::casa+	  File "/home/rramij/uGMRTprimarybeamCASA6/gotasks/ugmrtpb.py", line 611, in __call__
2024-03-14 07:07:57	INFO	ugmrtpb::::casa+	    _return_result_ = _ugmrtpb_t( _invocation_parameters['vis'],_invocation_parameters['imagename'],_invocation_parameters['nterms'],_invocation_parameters['threshold'],_invocation_parameters['action'],_invocation_parameters['reffreq'],_invocation_parameters['pbmin'],_invocation_parameters['field'],_invocation_parameters['spwlist'],_invocation_parameters['chanlist'],_invocation_parameters['weightlist'] )
2024-03-14 07:07:57	INFO	ugmrtpb::::casa+	  File "/home/rramij/uGMRTprimarybeamCASA6/ugmrtpb.py", line 190, in __call__
2024-03-14 07:07:57	INFO	ugmrtpb::::casa+	    task_result = _ugmrtpb_t( _pc.document['vis'], _pc.document['imagename'], _pc.document['nterms'], _pc.document['threshold'], _pc.document['action'], _pc.document['reffreq'], _pc.document['pbmin'], _pc.document['field'], _pc.document['spwlist'], _pc.document['chanlist'], _pc.document['weightlist'] )
2024-03-14 07:07:57	INFO	ugmrtpb::::casa+	  File "/home/rramij/uGMRTprimarybeamCASA6/private/task_ugmrtpb.py", line 145, in ugmrtpb
2024-03-14 07:07:57	INFO	ugmrtpb::::casa+	    ret = _calcTaylorFromCube(imtemplate=imagename+'.image.tt0',reffreq=reffreq,cubename=pbcubename,newtay=pblist, pbthreshold=pbthreshold, weightlist=weightlist);
2024-03-14 07:07:57	INFO	ugmrtpb::::casa+	  File "/home/rramij/uGMRTprimarybeamCASA6/private/task_ugmrtpb.py", line 354, in _calcTaylorFromCube
2024-03-14 07:07:57	INFO	ugmrtpb::::casa+	    ptays=_linfit(ptays, freqs, pbcube[:,:,0,:], weightarr, pbthreshold);
2024-03-14 07:07:57	INFO	ugmrtpb::::casa+	  File "/home/rramij/uGMRTprimarybeamCASA6/private/task_ugmrtpb.py", line 404, in _linfit
2024-03-14 07:07:57	INFO	ugmrtpb::::casa+	    invhess = linalg.inv(hess);
2024-03-14 07:07:57	INFO	ugmrtpb::::casa+	  File "/home/rramij/CASA/casa-6.4.1-12-pipeline-2022.2.0.64/lib/py/lib/python3.6/site-packages/scipy/linalg/basic.py", line 950, in inv
2024-03-14 07:07:57	INFO	ugmrtpb::::casa+	    a1 = _asarray_validated(a, check_finite=check_finite)
2024-03-14 07:07:57	INFO	ugmrtpb::::casa+	  File "/home/rramij/CASA/casa-6.4.1-12-pipeline-2022.2.0.64/lib/py/lib/python3.6/site-packages/scipy/_lib/_util.py", line 246, in _asarray_validated
2024-03-14 07:07:57	INFO	ugmrtpb::::casa+	    a = toarray(a)
2024-03-14 07:07:57	INFO	ugmrtpb::::casa+	  File "/home/rramij/CASA/casa-6.4.1-12-pipeline-2022.2.0.64/lib/py/lib/python3.6/site-packages/numpy/lib/function_base.py", line 499, in asarray_chkfinite
2024-03-14 07:07:57	INFO	ugmrtpb::::casa+	    "array must not contain infs or NaNs")
2024-03-14 07:07:57	INFO	ugmrtpb::::casa+	ValueError: array must not contain infs or NaNs
````
On the terminal, the following error pops up.
`/home/rramij/uGMRTprimarybeamCASA6/private/task_ugmrtpb.py:399: RuntimeWarning: overflow encountered in power
  hess[ii,jj]= np.mean( freqs**(ii+jj) * wts);
2024-03-14 07:26:18	SEVERE	widebandpbcor::::casa	Task ugmrtpb raised an exception of class ValueError with the following message: array must not contain infs or NaNs
2024-03-14 07:26:18	SEVERE	ugmrtpb::::casa	Exception Reported: Error in ugmrtpb: array must not contain infs or NaNs`
Please help me out with this.

**Comment by ruta-k** [comment]
Hi. Did your image contain NAN or inf pixels ? That might be an issue as shown in the error. Just guessing, as I have never faced this issue. How was the image generated ?
